'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, ChevronLeft, ChevronRight, Menu, Phone, MessageCircle, MapPin, X } from 'lucide-react'

type SchoolContent = { title: string; article: string; images: string[] }

function ContactSection() {
  return <section className="contact-strip content-contact"><div className="wide contact-inner"><div><span className="kicker purple">Come and visit</span><h2>Ready to elevate<br />your child&apos;s<br />educational journey?</h2></div><div className="contact-details"><h2>Contact Us</h2><p><span className="contact-phone"><Phone size={17} /><a href="tel:+254734323218">+254 734 323 218</a><a className="whatsapp-link" href="https://wa.me/254734323218" target="_blank" rel="noreferrer" aria-label="WhatsApp +254 734 323 218"><MessageCircle size={18} /></a></span><span className="contact-phone"><Phone size={17} /><a href="tel:+254728601575">+254 728 601 575</a><a className="whatsapp-link" href="https://wa.me/254728601575" target="_blank" rel="noreferrer" aria-label="WhatsApp +254 728 601 575"><MessageCircle size={18} /></a></span>Nairobi–Magadi Highway, Ongata Rongai, Kajiado County, Kenya<br /><a href="mailto:admin@laiserhillacademy.education">admin@laiserhillacademy.education</a></p><a className="map-link" href="https://maps.app.goo.gl/B8zAkXqzRtqk4zUcA" target="_blank" rel="noreferrer"><MapPin size={17} /> View Laiser Hill Academy on Google Maps</a></div></div></section>
}

export function SchoolContentPage({ content, backLabel = 'Back to home' }: { content: SchoolContent; backLabel?: string }) {
  const [galleryActive, setGalleryActive] = useState(0)
  const isAdmissions = content.title === 'Admissions'
  useEffect(() => { const timer = window.setInterval(() => setGalleryActive((current) => (current + 1) % content.images.length), 4200); return () => window.clearInterval(timer) }, [content.images.length])
  const paragraphs = content.article.split(/\n+/).map((paragraph) => paragraph.trim()).filter(Boolean).filter((paragraph) => !['7 aside football for U16 players.', 'A well equipped pitch for this upcoming sport.', '7 aside football for U16 players', 'A well equipped pitch for this upcoming sport'].includes(paragraph))
  const normalParagraphs = new Set(['Our primary school structure serves learners aged 6 to 14 years:', 'Our expansive grounds feature dedicated spaces for:', 'Chess and Scrabble', 'Arts and Entertainment', 'We welcome both boys and girls, offering flexible enrollment choices:', 'Chess and Scrabble.', 'Badminton, lawn tennis and table tennis', 'Upon completing IGCSE, students progress to our rigorous Advanced Level program:', 'Our campus boasts world-class sporting facilities and elite coaching programs:', 'Mathematics, English, Kiswahili, French', 'Chemistry, Physics, Biology', 'Geography, History, Religious Studies, Business Studies', 'Information and Communication Technology (ICT)', 'Mathematics, English, Law, Economics, Business', 'Geography, History', 'Physics, Chemistry, Biology'])
  const boldParagraphs = new Set(['Subjects Offered at IGCSE:', 'Subjects Offered at A-Level:', 'Year 12: Advanced Subsidiary (AS Level)', 'Year 13: Advanced Level (A2)'])
  const isNormalParagraph = (p: string) => normalParagraphs.has(p) || /^(chess and scrabble|badminton|lawn tennis|table tennis|our expansive grounds feature)/i.test(p)
  const isBoldParagraph = (p: string) => boldParagraphs.has(p) || /^year 1[23]\b/i.test(p) || /^subjects offered at (igcse|a-level)/i.test(p)
  const isSubheading = (p: string) => p.length < 85 && !/[.!?]$/.test(p) && !isNormalParagraph(p) && !isBoldParagraph(p) && !/^\d+\.?\s/.test(p)
  const formatParagraph = (p: string) => p.replace(/^\d+\.?\s*/, '')
  const [navOpen, setNavOpen] = useState(false)
  return <main className="content-page">
    <div className="utility"><div className="wide"><span>Learn with purpose. Lead with character.</span><span>Ongata Rongai · Nairobi, Kenya</span></div></div>
    <header className="main-header content-main-header"><div className="wide header-inner"><Link href="/" className="brand"><img className="crest-image" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lha%20logo1.jpg-oGRSIURLiTgyx3F1vNGX76ltTOYILZ.png" alt="Laiser Hill Academy crest logo" /><span><b>Laiser Hill Academy</b><em>To greater heights</em></span></Link><button className="mobile-toggle" onClick={() => setNavOpen(!navOpen)} aria-label="Toggle navigation" aria-expanded={navOpen}>{navOpen ? <X /> : <Menu />}</button><nav className={navOpen ? 'nav open' : 'nav'} aria-label="Primary navigation"><Link href="/" onClick={() => setNavOpen(false)}>Home</Link><div className="nav-dropdown"><button type="button">About us</button><div className="dropdown-menu"><Link href="/#welcome">Welcome</Link><Link href="/#our-history">Our History</Link><Link href="/#vision-mission">Vision, Mission &amp; Values</Link><Link href="/#leadership">School Leadership</Link><Link href="/#contact">Our Campus</Link></div></div><div className="nav-dropdown"><button type="button">Academics</button><div className="dropdown-menu"><Link href="/academics/kindergarten">Kindergarten</Link><Link href="/academics/primary-junior">Primary &amp; Junior School</Link><Link href="/academics/senior-school">Senior School</Link><Link href="/academics/international-school">International School</Link></div></div><div className="nav-dropdown"><button type="button">Admissions</button><div className="dropdown-menu"><Link href="/admissions">Admissions</Link><Link href="/admissions/fees">Fees</Link></div></div><Link href="/#contact">Contact</Link><a className="nav-service-link" href="https://lha.mzizi.co.ke/ISIMSLogin.aspx" target="_blank" rel="noreferrer">Student&apos;s Portal</a><a className="nav-service-link" href="https://laiserhillacademy.moodlecloud.com/login/index.php" target="_blank" rel="noreferrer">Online Learning</a><Link className="nav-cta" href="/admissions">Enquire now <ArrowRight size={15} /></Link></nav></div></header>
    <div className="content-backbar"><div className="wide"><Link href="/" className="back-link">{backLabel} <ArrowRight size={15} /></Link></div></div>
    <section className="content-hero"><div className="wide"><span className="kicker purple">Laiser Hill Academy</span><h1>{content.title}</h1><div className="content-hero-rule" /></div></section>
    <section className="article-section"><div className="wide"><article className="article-copy article-full-width"><p className="article-intro">{formatParagraph(paragraphs[0])}</p>{paragraphs.slice(1).map((paragraph, index) => { const display = formatParagraph(paragraph); const key = `${paragraph.slice(0, 20)}-${index}`; if (paragraph.startsWith('"') && paragraph.endsWith('"')) return <p className="article-quote" key={key}><strong><em>{display}</em></strong></p>; if (isBoldParagraph(paragraph)) return <p className="article-bold-line" key={key}><strong>{display}</strong></p>; if (isSubheading(paragraph)) return <h2 className="article-subheading" key={key}>{display}</h2>; return <p key={key}>{display}</p> })}</article></div></section>
    {!isAdmissions && <section className="school-gallery"><div className="wide"><div className="gallery-title-row"><div><span className="kicker purple">Inside our school</span><h2>{content.title} gallery</h2></div><div className="gallery-controls"><button onClick={() => setGalleryActive((galleryActive - 1 + content.images.length) % content.images.length)} aria-label="Previous gallery image"><ChevronLeft size={18} /></button><button onClick={() => setGalleryActive((galleryActive + 1) % content.images.length)} aria-label="Next gallery image"><ChevronRight size={18} /></button></div></div><div className="school-gallery-frame"><img className="gallery-image-blur" src={content.images[galleryActive]} alt="" aria-hidden="true" /><button className="gallery-side-control gallery-side-control-prev" onClick={() => setGalleryActive((galleryActive - 1 + content.images.length) % content.images.length)} aria-label="Previous gallery image"><ChevronLeft size={22} /></button><img className="gallery-image-main" src={content.images[galleryActive]} alt={`${content.title} gallery image ${galleryActive + 1}`} /><button className="gallery-side-control gallery-side-control-next" onClick={() => setGalleryActive((galleryActive + 1) % content.images.length)} aria-label="Next gallery image"><ChevronRight size={22} /></button><span>{String(galleryActive + 1).padStart(2, '0')} / {String(content.images.length).padStart(2, '0')}</span></div></div></section>}
    {isAdmissions && <ContactSection />}
    <footer className="content-footer"><div className="wide"><span>© 2026 Laiser Hill Academy</span><Link href="/">Return to laiserhill.academy</Link></div></footer>
  </main>
}
