import Link from 'next/link'
import { ArrowRight, Download } from 'lucide-react'

export const metadata = { title: 'Fees Structure 2026 | Laiser Hill Academy', description: 'View Laiser Hill Academy 2026 primary, secondary and international school fees, payment procedures and downloadable fee structures.' }

const primaryRows = [['Play Group','Kshs. 36,900','N/A'],['PP1 & PP2','Kshs. 49,860','N/A'],['Grade 1, 2 & 3','Kshs. 61,860','N/A'],['Grade 4, 5 & 6','Kshs. 68,850','Kshs. 95,000'],['Grade 7 & 8','Kshs. 78,000','Kshs. 110,000']]
const secondaryRows = [['CBE','Grade 9','Kshs. 88,000','Kshs. 110,000'],['CBE','Grade 10','Kshs. 88,000','Kshs. 110,000'],['KCSE','Form 3','Kshs. 113,020','Kshs. 150,950'],['KCSE','Form 4','Kshs. 113,020','Kshs. 150,950'],['IGCSE','Year 8 & 9','Kshs. 115,730','Kshs. 149,800'],['IGCSE','Year 10 & 11','Kshs. 116,774','Kshs. 154,021'],['A-Levels (IAL)','Year 12 & 13','Kshs. 96,300','Kshs. 145,000']]

export default function FeesPage() { return <main className="content-page"><div className="utility"><div className="wide"><span>Learn with purpose. Lead with character.</span><span>Ongata Rongai · Nairobi, Kenya</span></div></div><header className="main-header content-main-header"><div className="wide header-inner"><Link href="/" className="brand"><img className="crest-image" src="/images/lh/lha-logo.png" alt="Laiser Hill Academy crest" /><span><b>Laiser Hill Academy</b><em>To greater heights</em></span></Link><nav className="nav"><Link href="/">Home</Link><Link href="/admissions">Admissions</Link><Link href="/admissions/fees">Fees</Link><Link className="nav-cta" href="/admissions">Enquire now <ArrowRight size={15} /></Link></nav></div></header><div className="content-backbar"><div className="wide"><Link href="/admissions" className="back-link">Back to admissions <ArrowRight size={15} /></Link></div></div><section className="content-hero"><div className="wide"><span className="kicker purple">Admissions</span><h1>Fees Structure 2026</h1><div className="content-hero-rule" /></div></section><section className="fees-section"><div className="wide"><p className="fees-lead">Transparent, comprehensive fees for every academic stream. Tuition and boarding fees are payable per term unless otherwise stated.</p><div className="download-grid"><a className="download-card" href="/documents/primary-fee-structure-2026.pdf" download><Download size={20} /><span><strong>Primary Fee Structure</strong><small>Download PDF · 2026</small></span></a><a className="download-card" href="/documents/secondary-fee-structure-2026.pdf" download><Download size={20} /><span><strong>High School Fee Structure</strong><small>Download PDF · 2026</small></span></a></div><h2>Preschool &amp; Primary School</h2><div className="fee-table-wrap"><table><thead><tr><th>Class / Level</th><th>Day Scholar</th><th>Boarding</th></tr></thead><tbody>{primaryRows.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><h2>High School: Secondary &amp; International</h2><div className="fee-table-wrap"><table><thead><tr><th>Pathway</th><th>Form / Grade / Year</th><th>Day Fee</th><th>Boarding</th></tr></thead><tbody>{secondaryRows.map((row) => <tr key={row.join('-')}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><div className="fee-notes"><h2>Additional information</h2><p>Admission fee: Kshs. 9,500, payable once and non-refundable. Medical fee for boarders is Kshs. 3,500 per term. Primary student portal fee is Kshs. 1,100 per term.</p><p>Fees must be paid in full before reporting. The school does not accept cash. Please use the official bank accounts or KCB Paybill 522123, account format 83947K + Student Name + Class, and obtain an official receipt.</p></div></div></section><footer className="content-footer"><div className="wide"><span>© 2026 Laiser Hill Academy</span><Link href="/">Return home</Link></div></footer></main> }
